apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: notifications-svc-credentials-vault
  namespace: notifications-system
spec:
  vaultAuthRef: rabbitmq/vault-auth-prod
  mount: secret
  path: rabbitmq/notifications
  type: kv-v2
  destination:
    name: notifications-svc-credentials
    create: true
