apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  name: rabbitmq-client-cert
  namespace: notifications-system
spec:
  vaultAuthRef: rabbitmq/vault-auth-prod
  mount: pki
  role: rabbitmq-role
  commonName: notifications-svcuser.rabbitmq.svc.cluster.local
  format: pem
  ttl: 24h
  destination:
    create: true
    name: rabbitmq-client-cert
    type: kubernetes.io/tls
